"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { useRouter, usePathname } from "next/navigation";

type Language = "tr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation object
const translations = {
  tr: {
    // Navigation
    "nav.about": "Hakkımızda",
    "nav.courses": "Kurslar",
    "nav.exams": "Sınavlar",
    "nav.overseas": "Uluslararası Eğitim",
    "nav.blog": "Blog",
    "nav.login": "Giriş Yap",
    
    // Hero Section
    "hero.title": "IYN İLE BAŞARININ FORMULU",
    "hero.titleHighlight": "SANA ÖZEL",
    "hero.subtitle": "Standart planları unutun. Sizin potansiyelinize, hedeflerinize ve öğrenme stilinize en uygun yol haritasını birlikte çiziyoruz.",
    "hero.cta": "Kayıt Ol",
    
    // Education Cards
    "education.title": "KİŞİYE ÖZEL TASARLANMIŞ EĞİTİM MODELİ",
    "education.description": "Standart planları unutun. Sizin potansiyelinize, hedeflerinize ve öğrenme stilinize en uygun yol haritasını birlikte çiziyoruz.",
    
    // Online Education
    "online.title": "Online Eğitim ve Sınav İmkanları ile",
    "online.titleHighlight": "IYN'de Eğitim Çok Kolay",
    
    // Why IYN
    "why.title": "Neden",
    "why.titleHighlight": "IYN?",
    "why.feature1.title": "UZMAN LIDERLİĞİNDE VIDEO DERSLER",
    "why.feature1.desc": "Sektör profesyonellerinden yüksek kaliteli video kurslarımızla öğrenin.",
    "why.feature2.title": "GERÇEKÇİ SINAV SİMÜLATÖRLERİ",
    "why.feature2.desc": "Gerçeğini yansıtan sınavlarla pratik yaparak tam olarak hazır olduğunuzdan emin olun.",
    "why.feature3.title": "BİTİRME SERTİFİKALARI",
    "why.feature3.desc": "Yeni becerilerinizi özgeçmişinizde ve Linkedin'de sergilemek için sertifikalar kazanın.",
    
    // Exam Preparation
    "exam.subtitle": "SINAV HAZIRLIĞI",
    "exam.title": "Sınavlarınızı",
    "exam.titleHighlight": "Güvenle Geçin",
    "exam.description": "Sınav modülleri ile güçlü ve zayıf yönlerinizi belirleyin, gerçek sınav deneyimi yaşayın ve başarı için gereken avantajları elde edin.",
    "exam.feature1": "Binlerce pratik sorusu",
    "exam.feature2": "Süreli deneme sınavları",
    "exam.feature3": "Ayrıntılı performans raporları",
    "exam.cta": "Deneme Sınavına Başla",
    
    // Testimonials
    "testimonials.title": "Öğrencilerimiz",
    "testimonials.titleHighlight": "Ne Diyor?",
    "testimonial1.content": "IYN'in web geliştirme eğitimleri sayesinde kısa sürede iş buldum. Pratik odaklı yaklaşım ve gerçek projelerle çalışmak çok faydalı oldu.",
    "testimonial1.name": "Ahmet Mehmet",
    "testimonial1.role": "Web Developer",
    "testimonial2.content": "Sınav simülatörü gerçekten çok gerçekçi. Gerçek sınava girmeden önce kendimi test etme imkanı buldum ve başarılı oldum.",
    "testimonial2.name": "Mehmet Kaya",
    "testimonial2.role": "Data Scientist",
    "testimonial3.content": "UX/UI kursu ile tasarım prensiplerini öğrendim ve portfolyo oluşturdum. Mentör desteği çok değerliydi.",
    "testimonial3.name": "Zeynep Aydın",
    "testimonial3.role": "UX/UI Designer",
    
    // Footer
    "footer.courses": "Kurslar",
    "footer.company": "Şirket",
    "footer.support": "Destek",
    "footer.follow": "Bizi Takip Edin",
    "footer.copyright": "© 2024 IYN Education & Consultancy. Tüm hakları saklıdır.",
    
    // Stats
    "stats.students": "Mutlu Öğrenci",
    "stats.success": "Başarı Oranı",
    "stats.certificates": "Sertifika",
    
    // Contact
    "contact.visit": "Ofisimizi Ziyaret Edin",
    "contact.location": "IYN Education & Consultancy<br />İzmir, Turkey",
    "contact.phone": "+90 (XXX) XXX XX XX",
    "contact.email": "info@iyneducation.com",
    
    // About Us
    "about.hero.title": "EĞİTİMİN GELECEĞİNİ ŞEKİLLENDİRİYORUZ",
    "about.hero.subtitle": "IYN Eğitim olarak, her bireyin potansiyeline ulaşmasını sağlayan yenilikçi ve erişilebilir öğrenme çözümleri sunmaya adanmış bir ekibiz.",
    "about.mission.title": "MİSYONUMUZ",
    "about.mission.description": "En güncel teknolojileri ve pedagojik yaklaşımları kullanarak, her seviyeden öğrencinin hedeflerine ulaşmasını sağlayacak yüksek kaliteli, etkileşimli ve pratik eğitim içerikleri sunmak.",
    "about.vision.title": "VİZYONUMUZ",
    "about.vision.description": "Türkiye'de ve bölgede, yaşam boyu öğrenmeyi bir alışkanlık haline getiren, dijital eğitimin standartlarını belirleyen ve bireylerin kariyer yolculuklarında en güvendiği yol arkadaşı olmak.",
    "about.story.title": "BİZİM HİKAYEMİZ",
    "about.story.subtitle": "Öğrenme Tutkusundan Doğan Bir Platform",
    "about.story.paragraph1": "IYN Eğitim, 2020 yılında, teknolojinin gücünü kullanarak kaliteli eğitimi herkes için ulaşılabilir kılma hayaliyle kuruldu.",
    "about.story.paragraph2": "Küçük bir başlangıçtan, bugün binlerce öğrencinin kariyer hedeflerine ulaşmasına yardımcı olan, Türkiye'nin önde gelen online eğitim platformlarından birine dönüştük. Yolculuğumuz, sürekli öğrenme ve yenilikçilik tutkumuzla devam ediyor.",
    "about.story.paragraph3": "Eğitimde kaliteyi ve erişilebilirliği bir araya getirerek, öğrencilerimizin başarısını bizim başarımız olarak görüyoruz. Her gün daha iyi bir eğitim deneyimi sunmak için çalışmaya devam ediyoruz.",
    "about.team.title": "Ekibimizle Tanışın",
    "about.team.subtitle": "Başarımızın arkasındaki tutkulu insanlar.",
    "about.team.member1.name": "Ahmet Çelik",
    "about.team.member1.title": "Kurucu & CEO",
    "about.team.member2.name": "Elif Öztürk",
    "about.team.member2.title": "Eğitim Direktörü",
    "about.team.member3.name": "Mustafa Demir",
    "about.team.member3.title": "Teknoloji Lideri",
    "about.cta.title": "BİZİMLE BÜYÜMEYE HAZIR MISIN?",
    "about.cta.subtitle": "Ekibimize katılmak için bizimle iletişime geç!",
    "about.cta.button": "CV Yolla",
    
    // Courses
    "courses.hero.title": "DÜNYANIN EN İYİ ÜNİVERSİTELERİNE GİDEN YOL",
    "courses.hero.subtitle": "Advanced Placement (AP) ve International Baccalaureate (IB) programlarımızla yurt dışı eğitim hedeflerinize ulaşın.",
    "courses.programs.title": "AP ve IB Programları Nelerdir?",
    "courses.programs.description": "Bu programlar, lise öğrencilerine üniversite düzeyinde dersler alarak hem akademik olarak kendilerini kanıtlama hem de yurt dışındaki seçkin üniversitelerden kabul alma imkanı sunar.",
    "courses.ap.title": "Advanced Placement (AP)",
    "courses.ap.description": "College Board tarafından yönetilen AP programı, öğrencilere lisedeyken üniversite kredisi kazanma fırsatı verir. AP sınavlarında alınan yüksek notlar, üniversite başvurularında adayı öne çıkaran en önemli faktörlerdendir.",
    "courses.ib.title": "International Baccalaureate (IB)",
    "courses.ib.description": "IB Diploma Programı, öğrencileri eleştirel düşünmeye, sorgulamaya ve küresel bir bakış açısı kazanmaya teşvik eden, uluslararası geçerliliği olan zorlu bir müfredattır. Dünya genelindeki üniversiteler tarafından tanınır.",
    "courses.popular.title": "Popüler AP Kurslarımız",
    "courses.popular.subtitle": "Öğrencilerimizin en çok tercih ettiği ve en yüksek başarıyı yakaladığı dersler.",
    "courses.calculus.description": "Üniversite düzeyindeki kalkülüs konularını derinlemesine öğrenin ve problem çözme becerilerinizi geliştirin.",
    "courses.calculus.hours": "80 Saat Canlı Ders",
    "courses.calculus.level": "İleri Seviye",
    "courses.physics.description": "Kinematik, dinamik, elektrik ve manyetizma gibi temel fizik prensiplerini deney ve teori ile keşfedin.",
    "courses.physics.hours": "90 Saat Canlı Ders",
    "courses.physics.level": "Başlangıç",
    "courses.chemistry.description": "Atom teorisinden termodinamiğe kadar kimyanın temel taşlarını öğrenerek analitik yeteneklerinizi güçlendirin.",
    "courses.chemistry.hours": "80 Saat Canlı Ders",
    "courses.chemistry.level": "İleri Seviye",
    "courses.biology.description": "Canlıların temel işleyişini, evrimi ve ekolojiyi kapsayan geniş bir biyoloji müfredatına hakim olun.",
    "courses.biology.hours": "75 Saat Canlı Ders",
    "courses.biology.level": "İleri Seviye",
    "courses.economics.description": "Ekonomik prensipleri, pazar dinamiklerini ve küresel ekonomi politikalarını anlayarak dünyaya farklı bir gözle bakın.",
    "courses.economics.hours": "60 Saat Canlı Ders",
    "courses.economics.level": "Başlangıç",
    "courses.english.description": "İleri düzeyde okuma, analiz ve argüman geliştirme becerileri kazanarak akademik yazım yeteneğinizi zirveye taşıyın.",
    "courses.english.hours": "90 Saat Canlı Ders",
    "courses.english.level": "Başlangıç",
    "courses.why.title": "Hazırlığında Neden IYN?",
    "courses.features.experts.title": "Alanında Uzman Eğitmenler",
    "courses.features.experts.description": "Tüm eğitmenlerimiz AP ve IB müfredatlarında deneyimli, öğrencilere ilham veren uzmanlardır.",
    "courses.features.plans.title": "Kişiye Özel Çalışma Planları",
    "courses.features.plans.description": "Her öğrencinin güçlü ve zayıf yönlerini analiz ederek hedeflerine en verimli şekilde ulaşmasını sağlıyoruz.",
    "courses.features.consultancy.title": "Üniversite Başvuru Danışmanlığı",
    "courses.features.consultancy.description": "Sadece derslerde değil, okul seçimi, niyet mektubu yazımı ve başvuru sürecinin her aşamasında yanınızdayız.",
    "courses.cta.title": "Yurt Dışı Hayallerinize İlk Adımı Atın",
    "courses.cta.subtitle": "AP ve IB programlarımız hakkında daha fazla bilgi almak ve size özel yol haritamızı oluşturmak için eğitim danışmanlarımızla ücretsiz bir görüşme planlayın.",
    "courses.cta.button": "Ücretsiz Görüşme Al",
    
    // Exams
    "exams.hero.title": "ULUSLARARASI BAŞARININ KAPISINI ARALAYIN",
    "exams.hero.subtitle": "SAT, AP, IB ve Avrupa üniversiteleri giriş sınavlarına yönelik uzman rehberliğimiz, kapsamlı kaynaklarımız ve kişiye özel stratejilerimizle hedeflerinize ulaşın.",
    "exams.programs.title": "Hazırlık Programlarımız",
    "exams.programs.subtitle": "Hayalinizdeki üniversiteye giden yolda, ihtiyacınız olan her sınava yönelik özel hazırlık programları sunuyoruz.",
    "exams.programs.sat.title": "SAT & ACT Hazırlık",
    "exams.programs.sat.description": "ABD'deki üniversiteler için kritik öneme sahip SAT ve ACT sınavlarında en yüksek skoru hedefleyin. İngilizce ve Matematik bölümlerine yönelik stratejik dersler, deneme sınavları ve binlerce soruluk soru bankalarımızla yanınızdayız.",
    "exams.programs.apib.title": "AP & IB Sınavları",
    "exams.programs.apib.description": "Uluslararası geçerliliği olan AP ve IB sınavlarında üstün başarı göstererek en iyi üniversitelerden kabul ve kredi kazanın. Her branşa özel, derinlemesine konu anlatımları ve sınav odaklı pratik testleri sunuyoruz.",
    "exams.programs.european.title": "Avrupa Üniversiteleri Sınavları",
    "exams.programs.european.description": "Almanya için TestAS, İtalya'daki tıp fakülteleri için IMAT gibi ülkeye ve bölüme özel sınavlara yönelik butik hazırlık programlarımızla Avrupa'daki eğitim hedeflerinize ulaşmanızı sağlıyoruz.",
    "exams.programs.online.title": "Online Soru Bankası & Denemeler",
    "exams.programs.online.description": "Binlerce sorudan oluşan kapsamlı soru bankamız ve gerçek sınav koşullarını simüle eden deneme sınavlarımızla her zaman hazır olun. Performans analizi ve detaylı raporlarla gelişiminizi takip edin.",
    "exams.popular.title": "Popüler Deneme Sınavlarımız",
    "exams.popular.subtitle": "Öğrencilerimizin en çok tercih ettiği ve en yüksek başarıyı yakaladığı dersler.",
    "exams.popular.sat.title": "SAT DENEME",
    "exams.popular.sat.description": "Üniversite düzeyindeki kalkülüs konularını derinlemesine öğrenin ve problem çözme becerilerinizi geliştirin.",
    "exams.popular.sat.modules": "20 Modül",
    "exams.popular.sat.price": "Ücretsiz",
    "exams.popular.ap.title": "AP DENEME",
    "exams.popular.ap.description": "Kinematik, dinamik, elektrik ve manyetizma gibi temel fizik prensiplerini deney ve teori ile keşfedin.",
    "exams.popular.ap.modules": "12 Modül",
    "exams.popular.ap.price": "Ücretsiz",
    "exams.popular.ib.title": "IB DENEME",
    "exams.popular.ib.description": "Atom teorisinden termodinamiğe kadar kimyanın temel taşlarını öğrenerek analitik yeteneklerinizi güçlendirin.",
    "exams.popular.ib.modules": "5 Modül",
    "exams.popular.ib.price": "Ücretsiz",
    "exams.plans.title": "Herkes İçin Esnek Planlar",
    "exams.plans.popular": "EN POPÜLER",
    "exams.plans.basic.title": "Temel",
    "exams.plans.basic.price": "199₺/ay",
    "exams.plans.basic.feature1": "Tüm kurslara erişim",
    "exams.plans.basic.feature2": "Kurs bitirme sertifikaları",
    "exams.plans.basic.feature3": "Sınav simülatörleri",
    "exams.plans.basic.feature4": "Performans analizi",
    "exams.plans.basic.button": "Planı Seç",
    "exams.plans.pro.title": "Pro",
    "exams.plans.pro.price": "299₺/ay",
    "exams.plans.pro.feature1": "Tüm kurslara erişim",
    "exams.plans.pro.feature2": "Kurs bitirme sertifikaları",
    "exams.plans.pro.feature3": "Sınav simülatörleri",
    "exams.plans.pro.feature4": "Performans analizi",
    "exams.plans.pro.button": "Planı Seç",
    "exams.plans.corporate.title": "Kurumsal",
    "exams.plans.corporate.price": "Bize Ulaşın",
    "exams.plans.corporate.feature1": "Tüm Pro özellikler",
    "exams.plans.corporate.feature2": "Ekip ilerleme takibi",
    "exams.plans.corporate.feature3": "Özel hesap yöneticisi",
    "exams.plans.corporate.feature4": "Toplu indirimler",
    "exams.plans.corporate.button": "Planı Seç",
    
    // Overseas Education
    "overseas.hero.title": "YURTDIŞINDA EĞİTİMİN YENİ NESİL ADRESİ",
    "overseas.hero.subtitle": "IYN Eğitim'in uzman danışmanlık hizmetiyle yurtdışı eğitim hayallerinizi gerçeğe dönüştürün. Başvuru sürecinden kabul aşamasına kadar her adımda yanınızdayız.",
    "overseas.intro.subtitle": "GELECEĞİNİZE YATIRIM YAPIN",
    "overseas.intro.title": "Yurtdışında Eğitimin Kapılarını Aralayın",
    "overseas.intro.paragraph1": "Yurtdışında eğitim almak, yalnızca akademik bilginizi derinleştirmekle kalmaz, aynı zamanda sizi küresel bir vatandaşa dönüştürür. Farklı bir ülkede yaşamak, yeni kültürler tanımak ve dünyanın dört bir yanından arkadaşlar edinmek, vizyonunuzu genişletir ve hayata bakış açınızı zenginleştirir.",
    "overseas.intro.paragraph2": "Uluslararası tanınırlığa sahip bir diploma, kariyer hedeflerinize ulaşmada size büyük bir avantaj sağlar. Edineceğiniz dil becerileri, bağımsız yaşama tecrübesi ve problem çözme yetenekleri, sizi profesyonel hayatta bir adım öne taşır. IYN Eğitim olarak, bu heyecan verici yolculuğun her aşamasında, doğru ülke ve üniversite seçiminden başvuru süreçlerine kadar size rehberlik etmek için buradayız.",
    "overseas.countries.title": "Eğitim Alabileceğiniz Popüler Ülkeler",
    "overseas.countries.subtitle": "Her biri kendine özgü fırsatlar sunan ülkeler hakkında bilgi alın ve sizin için en doğru olanı seçin.",
    "overseas.countries.detailsButton": "Detaylı Bilgi",
    "overseas.countries.england.title": "İNGİLTERE",
    "overseas.countries.england.description": "Prestijli üniversiteleriyle bilinen İngiltere, özellikle Tıp alanında ve Oxford, Cambridge gibi dünya lideri okullarda eğitim almak isteyenler için eşsiz fırsatlar sunar.",
    "overseas.countries.netherlands.title": "HOLLANDA",
    "overseas.countries.netherlands.description": "Yenilikçi eğitim anlayışı, İngilizce programların bolluğu ve uluslararası öğrenci dostu ortamıyla Hollanda, mühendislik ve sosyal bilimlerde öne çıkmaktadır.",
    "overseas.countries.germany.title": "ALMANYA",
    "overseas.countries.germany.description": "Teknoloji ve mühendislik alanında bir dünya devi olan Almanya, devlet üniversitelerinde sunduğu ücretsiz veya düşük ücretli eğitim imkanlarıyla dikkat çeker.",
    "overseas.countries.belgium.title": "BELÇİKA",
    "overseas.countries.belgium.description": "Avrupa'nın kalbinde yer alan Belçika, çok dilli kültürü ve uluslararası ilişkiler, politika gibi alanlardaki güçlü programlarıyla uluslararası bir kariyer hedefine sahip olanlar için idealdir.",
    "overseas.countries.switzerland.title": "İSVİÇRE",
    "overseas.countries.switzerland.description": "Yüksek yaşam standartları ve araştırma odaklı üniversiteleriyle İsviçre, özellikle finans, otelcilik ve doğa bilimleri alanlarında dünya çapında bir üne sahiptir.",
    "overseas.countries.spain.title": "İSPANYA",
    "overseas.countries.spain.description": "Canlı kültürü, tarihi zenginliği ve uygun yaşam maliyetleriyle İspanya, mimarlık, sanat tarihi ve işletme gibi alanlarda kaliteli eğitim sunar.",
    "overseas.countries.italy.title": "İTALYA",
    "overseas.countries.italy.description": "Tasarım, moda ve sanatın beşiği olan İtalya, bu alanlarda okumak isteyen öğrenciler için dünyanın en iyi okullarına ev sahipliği yapmaktadır. Tıp ve mühendislikte de güçlüdür.",
    "overseas.countries.canada.title": "KANADA",
    "overseas.countries.canada.description": "Güvenli ve çok kültürlü yapısıyla bilinen Kanada, özellikle bilgisayar bilimleri, yapay zeka ve işletme alanlarında dünya standartlarında eğitim ve mezuniyet sonrası çalışma imkanları sunar.",
    "overseas.countries.america.title": "AMERİKA",
    "overseas.countries.america.description": "Dünyanın en iyi üniversitelerinin çoğuna ev sahipliği yapan ABD, sunduğu esnek eğitim sistemi, araştırma olanakları ve kampüs hayatı ile her alanda sayısız fırsat sunar.",
    "overseas.cta.title": "Hayalinizdeki Ülkeyi Birlikte Keşfedelim",
    "overseas.cta.subtitle": "Uzman danışmanlarımızla birlikte, size en uygun ülke ve üniversiteyi belirleyelim. Başvuru sürecinizin her aşamasında yanınızda olacağız.",
    "overseas.cta.button": "Ücretsiz Danışmanlık Al",
    
    // Blog
    "blog.hero.title": "EĞİTİM DÜNYASINDAN HABERLER",
    "blog.hero.subtitle": "Eğitim, kariyer ve yurtdışı eğitim konularında güncel bilgiler, ipuçları ve uzman görüşleriyle bilgi dağarcığınızı genişletin.",
    "blog.categories.title": "Kategoriler",
    "blog.categories.subtitle": "İlgi alanınıza göre blog yazılarını keşfedin",
    "blog.categories.readMore": "Devamını Oku",
    "blog.categories.education.title": "Eğitim",
    "blog.categories.education.description": "Eğitim metodları, öğrenme teknikleri ve akademik gelişim hakkında bilgiler.",
    "blog.categories.exams.title": "Sınavlar",
    "blog.categories.exams.description": "SAT, AP, IB ve diğer uluslararası sınavlar hakkında ipuçları ve stratejiler.",
    "blog.categories.overseas.title": "Yurtdışı Eğitim",
    "blog.categories.overseas.description": "Yurtdışı eğitim fırsatları, üniversite seçimi ve başvuru süreçleri.",
    "blog.categories.career.title": "Kariyer",
    "blog.categories.career.description": "Kariyer planlama, iş fırsatları ve profesyonel gelişim tavsiyeleri.",
    "blog.categories.tips.title": "İpuçları",
    "blog.categories.tips.description": "Öğrenciler için pratik ipuçları ve başarı stratejileri.",
    "blog.categories.news.title": "Haberler",
    "blog.categories.news.description": "Eğitim dünyasından güncel haberler ve gelişmeler.",
    "blog.posts.title": "Son Yazılar",
    "blog.posts.subtitle": "En güncel blog yazılarımızı keşfedin",
    "blog.posts.readMore": "Devamını Oku",
    "blog.posts.loadMore": "Daha Fazla Yükle",
    "blog.featured.title": "2024'te Yurtdışı Eğitim Trendleri: Hangi Ülkeler Öne Çıkıyor?",
    "blog.featured.excerpt": "Yurtdışı eğitim dünyasında yaşanan değişimler ve 2024 yılında öğrencilerin tercih ettiği ülkeler hakkında detaylı bir analiz.",
    "blog.featured.author": "IYN Eğitim Ekibi",
    "blog.featured.date": "15 Aralık 2024",
    "blog.featured.category": "Yurtdışı Eğitim",
    "blog.featured.readTime": "8 dk okuma",
    "blog.posts.post1.title": "SAT Sınavına Hazırlanmanın En Etkili Yolları",
    "blog.posts.post1.excerpt": "SAT sınavında başarılı olmak için uygulamanız gereken stratejiler ve çalışma teknikleri.",
    "blog.posts.post1.author": "Dr. Ahmet Yılmaz",
    "blog.posts.post1.date": "12 Aralık 2024",
    "blog.posts.post1.category": "Sınavlar",
    "blog.posts.post1.readTime": "5 dk okuma",
    "blog.posts.post2.title": "AP Kursları ile Üniversite Kredisi Kazanma",
    "blog.posts.post2.excerpt": "AP kurslarının avantajları ve üniversite başvurularında nasıl fark yaratabileceğiniz.",
    "blog.posts.post2.author": "Elif Öztürk",
    "blog.posts.post2.date": "10 Aralık 2024",
    "blog.posts.post2.category": "Eğitim",
    "blog.posts.post2.readTime": "6 dk okuma",
    "blog.posts.post3.title": "Almanya'da Ücretsiz Üniversite Eğitimi",
    "blog.posts.post3.excerpt": "Almanya'daki üniversitelerde ücretsiz eğitim alma koşulları ve başvuru süreçleri.",
    "blog.posts.post3.author": "Mustafa Demir",
    "blog.posts.post3.date": "8 Aralık 2024",
    "blog.posts.post3.category": "Yurtdışı Eğitim",
    "blog.posts.post3.readTime": "7 dk okuma",
    "blog.posts.post4.title": "IB Diploma Programının Avantajları",
    "blog.posts.post4.excerpt": "IB programının öğrencilere sağladığı akademik ve kişisel gelişim fırsatları.",
    "blog.posts.post4.author": "Prof. Dr. Zeynep Kaya",
    "blog.posts.post4.date": "5 Aralık 2024",
    "blog.posts.post4.category": "Eğitim",
    "blog.posts.post4.readTime": "4 dk okuma",
    "blog.posts.post5.title": "Kariyer Planlamasında Yurtdışı Deneyiminin Rolü",
    "blog.posts.post5.excerpt": "Yurtdışı eğitim deneyiminin kariyerinize katkıları ve iş hayatında fark yaratma yolları.",
    "blog.posts.post5.author": "Dr. Can Özkan",
    "blog.posts.post5.date": "3 Aralık 2024",
    "blog.posts.post5.category": "Kariyer",
    "blog.posts.post5.readTime": "6 dk okuma",
    "blog.posts.post6.title": "Üniversite Başvuru Sürecinde Yapılan Hatalar",
    "blog.posts.post6.excerpt": "Yurtdışı üniversite başvurularında sıkça yapılan hatalar ve bunlardan kaçınma yolları.",
    "blog.posts.post6.author": "IYN Danışman Ekibi",
    "blog.posts.post6.date": "1 Aralık 2024",
    "blog.posts.post6.category": "İpuçları",
    "blog.posts.post6.readTime": "5 dk okuma",
    "blog.newsletter.title": "Blog Güncellemelerini Kaçırmayın",
    "blog.newsletter.subtitle": "En yeni blog yazılarımız ve eğitim dünyasından haberler doğrudan e-posta kutunuza gelsin.",
    "blog.newsletter.emailPlaceholder": "E-posta adresiniz",
    "blog.newsletter.subscribeButton": "Abone Ol",
    "blog.newsletter.privacy": "E-posta adresiniz güvende. İstediğiniz zaman abonelikten çıkabilirsiniz.",
  },
  en: {
    // Navigation
    "nav.about": "About Us",
    "nav.courses": "Courses",
    "nav.exams": "Exams",
    "nav.overseas": "International Education",
    "nav.blog": "Blog",
    "nav.login": "Login",
    
    // Hero Section
    "hero.title": "THE FORMULA FOR SUCCESS WITH IYN IS",
    "hero.titleHighlight": "SPECIAL TO YOU",
    "hero.subtitle": "Forget standard plans. Together, we draw the most suitable roadmap for your potential, goals, and learning style.",
    "hero.cta": "Register Now",
    
    // Education Cards
    "education.title": "PERSONALLY DESIGNED EDUCATION MODEL",
    "education.description": "Forget standard plans. Together, we draw the most suitable roadmap for your potential, goals, and learning style.",
    
    // Online Education
    "online.title": "Education is Very Easy with IYN's",
    "online.titleHighlight": "Online Education and Exam Opportunities",
    
    // Why IYN
    "why.title": "Why",
    "why.titleHighlight": "IYN?",
    "why.feature1.title": "VIDEO LESSONS WITH EXPERT LEADERSHIP",
    "why.feature1.desc": "Learn with high-quality video courses from industry professionals.",
    "why.feature2.title": "REALISTIC EXAM SIMULATORS",
    "why.feature2.desc": "Practice with realistic exams and be sure you are fully prepared.",
    "why.feature3.title": "COMPLETION CERTIFICATES",
    "why.feature3.desc": "Earn certificates to showcase your new skills on your resume and LinkedIn.",
    
    // Exam Preparation
    "exam.subtitle": "EXAM PREPARATION",
    "exam.title": "Pass Your Exams",
    "exam.titleHighlight": "Confidently",
    "exam.description": "Identify your strengths and weaknesses with exam modules, experience real exam conditions, and gain the advantages needed for success.",
    "exam.feature1": "Thousands of practice questions",
    "exam.feature2": "Timed practice exams",
    "exam.feature3": "Detailed performance reports",
    "exam.cta": "Start Practice Exam",
    
    // Testimonials
    "testimonials.title": "What Do Our Students",
    "testimonials.titleHighlight": "Say?",
    "testimonial1.content": "Thanks to IYN's web development training, I found a job quickly. The practical approach and working with real projects was very beneficial.",
    "testimonial1.name": "Ahmet Mehmet",
    "testimonial1.role": "Web Developer",
    "testimonial2.content": "The exam simulator is really realistic. I had the opportunity to test myself before taking the real exam and succeeded.",
    "testimonial2.name": "Mehmet Kaya",
    "testimonial2.role": "Data Scientist",
    "testimonial3.content": "I learned design principles with the UX/UI course and created a portfolio. The mentor support was very valuable.",
    "testimonial3.name": "Zeynep Aydın",
    "testimonial3.role": "UX/UI Designer",
    
    // Footer
    "footer.courses": "Courses",
    "footer.company": "Company",
    "footer.support": "Support",
    "footer.follow": "Follow Us",
    "footer.copyright": "© 2024 IYN Education & Consultancy. All rights reserved.",
    
    // Stats
    "stats.students": "Happy Students",
    "stats.success": "Success Rate",
    "stats.certificates": "Certificates",
    
    // Contact
    "contact.visit": "Visit Our Office",
    "contact.location": "IYN Education & Consultancy<br />İzmir, Turkey",
    "contact.phone": "+90 (XXX) XXX XX XX",
    "contact.email": "info@iyneducation.com",
    
    // About Us
    "about.hero.title": "WE ARE SHAPING THE FUTURE OF EDUCATION",
    "about.hero.subtitle": "As IYN Education, we are a team dedicated to providing innovative and accessible learning solutions that enable every individual to reach their potential.",
    "about.mission.title": "OUR MISSION",
    "about.mission.description": "Using the latest technologies and pedagogical approaches, to provide high-quality, interactive, and practical educational content that enables students of all levels to reach their goals.",
    "about.vision.title": "OUR VISION",
    "about.vision.description": "In Turkey and the region, to make lifelong learning a habit, set digital education standards, and be the most trusted companion for individuals in their career journeys.",
    "about.story.title": "OUR STORY",
    "about.story.subtitle": "A Platform Born from the Passion for Learning",
    "about.story.paragraph1": "IYN Education was founded in 2020 with the dream of making quality education accessible to everyone by leveraging the power of technology.",
    "about.story.paragraph2": "From a small beginning, today we have become one of Turkey's leading online education platforms, helping thousands of students achieve their career goals. Our journey continues with our passion for continuous learning and innovation.",
    "about.story.paragraph3": "By combining quality and accessibility in education, we see our students' success as our success. We continue to work to provide a better educational experience every day.",
    "about.team.title": "Meet Our Team",
    "about.team.subtitle": "The passionate people behind our success.",
    "about.team.member1.name": "Ahmet Çelik",
    "about.team.member1.title": "Founder & CEO",
    "about.team.member2.name": "Elif Öztürk",
    "about.team.member2.title": "Education Director",
    "about.team.member3.name": "Mustafa Demir",
    "about.team.member3.title": "Technology Leader",
    "about.cta.title": "READY TO GROW WITH US?",
    "about.cta.subtitle": "Contact us to join our team!",
    "about.cta.button": "Send CV",
    
    // Courses
    "courses.hero.title": "THE PATH TO THE WORLD'S BEST UNIVERSITIES",
    "courses.hero.subtitle": "Reach your overseas education goals with our Advanced Placement (AP) and International Baccalaureate (IB) programs.",
    "courses.programs.title": "What are AP and IB Programs?",
    "courses.programs.description": "These programs offer high school students the opportunity to take university-level courses, prove themselves academically, and gain admission to prestigious universities abroad.",
    "courses.ap.title": "Advanced Placement (AP)",
    "courses.ap.description": "The AP program, managed by the College Board, gives students the opportunity to earn university credits while in high school. High scores on AP exams are among the most important factors that make a candidate stand out in university applications.",
    "courses.ib.title": "International Baccalaureate (IB)",
    "courses.ib.description": "The IB Diploma Program is a challenging curriculum with international validity that encourages students to develop critical thinking, inquiry, and a global perspective. It is recognized by universities worldwide.",
    "courses.popular.title": "Popular AP Courses",
    "courses.popular.subtitle": "The most preferred courses by our students and the ones with the highest success.",
    "courses.calculus.description": "Learn university-level calculus topics in depth and develop your problem-solving skills.",
    "courses.calculus.hours": "80 Hours Live Class",
    "courses.calculus.level": "Advanced Level",
    "courses.physics.description": "Explore fundamental physics principles like kinematics, dynamics, electricity, and magnetism through experiment and theory.",
    "courses.physics.hours": "90 Hours Live Class",
    "courses.physics.level": "Beginner",
    "courses.chemistry.description": "Strengthen your analytical skills by learning the cornerstones of chemistry, from atomic theory to thermodynamics.",
    "courses.chemistry.hours": "80 Hours Live Class",
    "courses.chemistry.level": "Advanced Level",
    "courses.biology.description": "Master a broad biology curriculum covering the fundamental functioning of living things, evolution, and ecology.",
    "courses.biology.hours": "75 Hours Live Class",
    "courses.biology.level": "Advanced Level",
    "courses.economics.description": "Look at the world with a different eye by understanding economic principles, market dynamics, and global economic policies.",
    "courses.economics.hours": "60 Hours Live Class",
    "courses.economics.level": "Beginner",
    "courses.english.description": "Elevate your academic writing skills by gaining advanced reading, analysis, and argument development abilities.",
    "courses.english.hours": "90 Hours Live Class",
    "courses.english.level": "Beginner",
    "courses.why.title": "Why IYN for AP/IB Preparation?",
    "courses.features.experts.title": "Expert Trainers in Their Field",
    "courses.features.experts.description": "All our trainers are experienced in AP and IB curricula, experts who inspire students.",
    "courses.features.plans.title": "Personalized Study Plans",
    "courses.features.plans.description": "We enable each student to reach their goals most efficiently by analyzing their strengths and weaknesses.",
    "courses.features.consultancy.title": "University Application Consultancy",
    "courses.features.consultancy.description": "We are with you not only in lessons but also in every stage of the application process, including school selection and letter of intent writing.",
    "courses.cta.title": "Take the First Step Towards Your Dreams Abroad",
    "courses.cta.subtitle": "To get more information about our AP and IB programs and create your personalized roadmap, schedule a free consultation with our education consultants.",
    "courses.cta.button": "Get a Free Consultation",
    
    // Exams
    "exams.hero.title": "OPEN THE DOOR TO INTERNATIONAL SUCCESS",
    "exams.hero.subtitle": "Reach your goals with our expert guidance, comprehensive resources, and personalized strategies for SAT, AP, IB, and European university entrance exams.",
    "exams.programs.title": "Our Preparation Programs",
    "exams.programs.subtitle": "On the way to your dream university, we offer special preparation programs for every exam you need.",
    "exams.programs.sat.title": "SAT & ACT Preparation",
    "exams.programs.sat.description": "Aim for the highest score in SAT and ACT exams, which are critically important for universities in the USA. We are with you with strategic lessons for English and Mathematics sections, practice exams, and thousands of questions in our question banks.",
    "exams.programs.apib.title": "AP & IB Exams",
    "exams.programs.apib.description": "Achieve superior success in internationally recognized AP and IB exams to gain admission and credit from the best universities. We offer in-depth subject explanations and exam-focused practice tests specific to each branch.",
    "exams.programs.european.title": "European University Exams",
    "exams.programs.european.description": "We help you reach your educational goals in Europe with our boutique preparation programs for country and region-specific exams like TestAS for Germany and IMAT for medical faculties in Italy.",
    "exams.programs.online.title": "Online Question Bank & Practice Exams",
    "exams.programs.online.description": "Always be ready with our comprehensive question bank consisting of thousands of questions and practice exams that simulate real exam conditions. Track your progress with performance analysis and detailed reports.",
    "exams.popular.title": "Our Popular Practice Exams",
    "exams.popular.subtitle": "Courses most preferred by our students and achieving the highest success.",
    "exams.popular.sat.title": "SAT PRACTICE",
    "exams.popular.sat.description": "Learn university-level calculus topics in depth and improve your problem-solving skills.",
    "exams.popular.sat.modules": "20 Modules",
    "exams.popular.sat.price": "Free",
    "exams.popular.ap.title": "AP PRACTICE",
    "exams.popular.ap.description": "Explore fundamental physics principles like kinematics, dynamics, electricity, and magnetism through experiment and theory.",
    "exams.popular.ap.modules": "12 Modules",
    "exams.popular.ap.price": "Free",
    "exams.popular.ib.title": "IB PRACTICE",
    "exams.popular.ib.description": "Strengthen your analytical skills by learning the building blocks of chemistry, from atomic theory to thermodynamics.",
    "exams.popular.ib.modules": "5 Modules",
    "exams.popular.ib.price": "Free",
    "exams.plans.title": "Flexible Plans for Everyone",
    "exams.plans.popular": "MOST POPULAR",
    "exams.plans.basic.title": "Basic",
    "exams.plans.basic.price": "$19/month",
    "exams.plans.basic.feature1": "Access to all courses",
    "exams.plans.basic.feature2": "Course completion certificates",
    "exams.plans.basic.feature3": "Exam simulators",
    "exams.plans.basic.feature4": "Performance analysis",
    "exams.plans.basic.button": "Select Plan",
    "exams.plans.pro.title": "Pro",
    "exams.plans.pro.price": "$29/month",
    "exams.plans.pro.feature1": "Access to all courses",
    "exams.plans.pro.feature2": "Course completion certificates",
    "exams.plans.pro.feature3": "Exam simulators",
    "exams.plans.pro.feature4": "Performance analysis",
    "exams.plans.pro.button": "Select Plan",
    "exams.plans.corporate.title": "Corporate",
    "exams.plans.corporate.price": "Contact Us",
    "exams.plans.corporate.feature1": "All Pro features",
    "exams.plans.corporate.feature2": "Team progress tracking",
    "exams.plans.corporate.feature3": "Dedicated account manager",
    "exams.plans.corporate.feature4": "Bulk discounts",
    "exams.plans.corporate.button": "Select Plan",
    
    // Overseas Education
    "overseas.hero.title": "THE NEW GENERATION ADDRESS OF EDUCATION ABROAD",
    "overseas.hero.subtitle": "Turn your overseas education dreams into reality with IYN Education's expert consultancy service. We are with you every step of the way, from the application process to the acceptance stage.",
    "overseas.intro.subtitle": "INVEST IN YOUR FUTURE",
    "overseas.intro.title": "Open the Doors to Overseas Education",
    "overseas.intro.paragraph1": "Studying abroad not only deepens your academic knowledge but also transforms you into a global citizen. Living in a different country, getting to know new cultures, and making friends from all over the world broadens your vision and enriches your perspective on life.",
    "overseas.intro.paragraph2": "An internationally recognized diploma provides a great advantage in achieving your career goals. The language skills, independent living experience, and problem-solving abilities you gain will take you a step further in your professional life. As IYN Education, we are here to guide you through every stage of this exciting journey, from choosing the right country and university to the application processes.",
    "overseas.countries.title": "Popular Countries Where You Can Get Education",
    "overseas.countries.subtitle": "Get information about countries that offer unique opportunities and choose the right one for you.",
    "overseas.countries.detailsButton": "Detailed Information",
    "overseas.countries.england.title": "ENGLAND",
    "overseas.countries.england.description": "Known for its prestigious universities, England offers unique opportunities for those who want to study, especially in Medicine, and at world-leading schools like Oxford and Cambridge.",
    "overseas.countries.netherlands.title": "NETHERLANDS",
    "overseas.countries.netherlands.description": "With its innovative education approach, abundance of English programs, and international student-friendly environment, the Netherlands stands out in engineering and social sciences.",
    "overseas.countries.germany.title": "GERMANY",
    "overseas.countries.germany.description": "Germany, a world giant in technology and engineering, stands out with the free or low-cost education opportunities it offers at state universities.",
    "overseas.countries.belgium.title": "BELGIUM",
    "overseas.countries.belgium.description": "Located in the heart of Europe, Belgium is ideal for those aiming for an international career with its strong programs in multilingual culture, international relations, and politics.",
    "overseas.countries.switzerland.title": "SWITZERLAND",
    "overseas.countries.switzerland.description": "With high living standards and research-focused universities, Switzerland has a worldwide reputation, especially in the fields of finance, hospitality, and natural sciences.",
    "overseas.countries.spain.title": "SPAIN",
    "overseas.countries.spain.description": "With its vibrant culture, rich history, and affordable living costs, Spain offers quality education in fields such as architecture, art history, and business.",
    "overseas.countries.italy.title": "ITALY",
    "overseas.countries.italy.description": "Italy, the cradle of design, fashion, and art, hosts some of the world's best schools for students wishing to study in these fields. It is also strong in medicine and engineering.",
    "overseas.countries.canada.title": "CANADA",
    "overseas.countries.canada.description": "Known for its safe and multicultural structure, Canada offers world-class education and post-graduation employment opportunities, especially in computer science, artificial intelligence, and business.",
    "overseas.countries.america.title": "AMERICA",
    "overseas.countries.america.description": "The USA, home to many of the world's best universities, offers countless opportunities in every field with its flexible education system, research facilities, and campus life.",
    "overseas.cta.title": "Let's Explore Your Dream Country Together",
    "overseas.cta.subtitle": "Together with our expert consultants, let's determine the most suitable country and university for you. We will be with you at every stage of your application process.",
    "overseas.cta.button": "Get Free Consultation",
    
    // Blog
    "blog.hero.title": "NEWS FROM THE EDUCATION WORLD",
    "blog.hero.subtitle": "Expand your knowledge base with current information, tips, and expert opinions on education, career, and overseas education topics.",
    "blog.categories.title": "Categories",
    "blog.categories.subtitle": "Discover blog posts according to your interests",
    "blog.categories.readMore": "Read More",
    "blog.categories.education.title": "Education",
    "blog.categories.education.description": "Information about education methods, learning techniques, and academic development.",
    "blog.categories.exams.title": "Exams",
    "blog.categories.exams.description": "Tips and strategies for SAT, AP, IB, and other international exams.",
    "blog.categories.overseas.title": "Overseas Education",
    "blog.categories.overseas.description": "Overseas education opportunities, university selection, and application processes.",
    "blog.categories.career.title": "Career",
    "blog.categories.career.description": "Career planning, job opportunities, and professional development advice.",
    "blog.categories.tips.title": "Tips",
    "blog.categories.tips.description": "Practical tips and success strategies for students.",
    "blog.categories.news.title": "News",
    "blog.categories.news.description": "Latest news and developments from the education world.",
    "blog.posts.title": "Latest Posts",
    "blog.posts.subtitle": "Discover our most recent blog posts",
    "blog.posts.readMore": "Read More",
    "blog.posts.loadMore": "Load More",
    "blog.featured.title": "2024 Overseas Education Trends: Which Countries Stand Out?",
    "blog.featured.excerpt": "A detailed analysis of changes in the overseas education world and countries preferred by students in 2024.",
    "blog.featured.author": "IYN Education Team",
    "blog.featured.date": "December 15, 2024",
    "blog.featured.category": "Overseas Education",
    "blog.featured.readTime": "8 min read",
    "blog.posts.post1.title": "Most Effective Ways to Prepare for the SAT Exam",
    "blog.posts.post1.excerpt": "Strategies and study techniques you should apply to succeed in the SAT exam.",
    "blog.posts.post1.author": "Dr. Ahmet Yılmaz",
    "blog.posts.post1.date": "December 12, 2024",
    "blog.posts.post1.category": "Exams",
    "blog.posts.post1.readTime": "5 min read",
    "blog.posts.post2.title": "Earning University Credits with AP Courses",
    "blog.posts.post2.excerpt": "Advantages of AP courses and how you can make a difference in university applications.",
    "blog.posts.post2.author": "Elif Öztürk",
    "blog.posts.post2.date": "December 10, 2024",
    "blog.posts.post2.category": "Education",
    "blog.posts.post2.readTime": "6 min read",
    "blog.posts.post3.title": "Free University Education in Germany",
    "blog.posts.post3.excerpt": "Conditions for receiving free education at German universities and application processes.",
    "blog.posts.post3.author": "Mustafa Demir",
    "blog.posts.post3.date": "December 8, 2024",
    "blog.posts.post3.category": "Overseas Education",
    "blog.posts.post3.readTime": "7 min read",
    "blog.posts.post4.title": "Advantages of the IB Diploma Programme",
    "blog.posts.post4.excerpt": "Academic and personal development opportunities that the IB program provides to students.",
    "blog.posts.post4.author": "Prof. Dr. Zeynep Kaya",
    "blog.posts.post4.date": "December 5, 2024",
    "blog.posts.post4.category": "Education",
    "blog.posts.post4.readTime": "4 min read",
    "blog.posts.post5.title": "The Role of Overseas Experience in Career Planning",
    "blog.posts.post5.excerpt": "Contributions of overseas education experience to your career and ways to make a difference in business life.",
    "blog.posts.post5.author": "Dr. Can Özkan",
    "blog.posts.post5.date": "December 3, 2024",
    "blog.posts.post5.category": "Career",
    "blog.posts.post5.readTime": "6 min read",
    "blog.posts.post6.title": "Mistakes Made in the University Application Process",
    "blog.posts.post6.excerpt": "Common mistakes in overseas university applications and ways to avoid them.",
    "blog.posts.post6.author": "IYN Consultant Team",
    "blog.posts.post6.date": "December 1, 2024",
    "blog.posts.post6.category": "Tips",
    "blog.posts.post6.readTime": "5 min read",
    "blog.newsletter.title": "Don't Miss Blog Updates",
    "blog.newsletter.subtitle": "Get our latest blog posts and education world news directly in your email inbox.",
    "blog.newsletter.emailPlaceholder": "Your email address",
    "blog.newsletter.subscribeButton": "Subscribe",
    "blog.newsletter.privacy": "Your email is safe with us. You can unsubscribe at any time.",
  }
};

interface LanguageProviderProps {
  children: ReactNode;
  initialLanguage?: Language;
}

export function LanguageProvider({ children, initialLanguage = "tr" }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(initialLanguage);
  const router = useRouter();
  const pathname = usePathname();

  // Sync language state with URL parameter on mount
  useEffect(() => {
    setLanguageState(initialLanguage);
  }, [initialLanguage]);

  // Handle language change with navigation
  const handleSetLanguage = (lang: Language) => {
    // Save preference
    localStorage.setItem("iyn-language", lang);
    
    // Navigate to the new language route
    // Extract the path after the language segment
    const pathSegments = pathname?.split('/').filter(Boolean) || [];
    const currentPath = pathSegments.slice(1).join('/');
    const newPath = currentPath ? `/${lang}/${currentPath}` : `/${lang}`;
    
    // Force a full page reload to ensure all animations reinitialize
    window.location.href = newPath;
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.tr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
